---
- Media:
    - YouTube:
        - icon: youtube.png
          href: https://www.youtube.com/
    - Reddit:
        - icon: reddit.png
          href: https://www.reddit.com/
    - DisneyPlus:
        - icon: disneyplus.png
          href: https://www.disneyplus.com/
          description: Disney+

- Social:
    - LinkedIn:
        - icon: linkedin.png
          href: https://www.linkedin.com/in/brandon-miner-3x3/
    - GitHub:
        - icon: github.png
          href: https://github.com/brandonminer333