---
- datetime:
    text_size: xl
    format:
      dateStyle: medium
      timeStyle: short
      hourCycle: h23

- search:
    provider: duckduckgo
    target: _blank

- resources:
    cpu: true
    memory: true
    disk: /
