services:
  pihole:
    image: pihole/pihole:latest
    container_name: Peryite
    networks:
      - Oblivion
    environment:
      TZ: America/Los_Angeles
      WEBPASSWORD: ${WEBPASSWORD}
    volumes:
      - ./pihole/etc-pihole:/etc/pihole
      - ./pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    restart: unless-stopped

networks:
  Oblivion:
    external: true