containers:
  forgejo:
    run: false
    depends-on: [mariadb]
  homepage:
    run: true
  immich:
    run: false
  jellyfin:
    run: false
  llm:
    run: false
    path: src/llm/mcp/public
  mariadb:
    run: true
  minecraft:
    run: false
  nginx:
    run: true
  ntfy:
    run: true
  onlyoffice:
    run: false
    depends-on: [mariadb]
  pihole:
    run: true
  qbittorrent:
    run: false
  radicale:
    run: false
  seafile:
    run: true
    depends-on: [mariadb]
  vaultwarden:
    run: true
  vscode:
    run: false
  watchtower:
    run: true
    depends-on: [ntfy]
