containers:
  forgejo:
    priority: 1
    runs: false
    depends-on: [mariadb]
  homepage:
    priority: 1
    runs: true
  immich:
    priority: 1
    runs: false
  jellyfin:
    priority: 1
    runs: false
  llm:
    priority: 1
    runs: false
    path: src/llm/mcp/public
  mariadb:
    priority: 1
    runs: true
  minecraft:
    priority: 1
    runs: false
  nginx:
    priority: 0
    runs: true
  ntfy:
    priority: 2
    runs: true
  libreoffice:
    priority: 1
    runs: true
  pihole:
    priority: 1
    runs: true
  qbittorrent:
    priority: 1
    runs: false
  radicale:
    priority: 1
    runs: false
  seafile:
    priority: 1
    runs: true
    depends-on: [mariadb]
  vaultwarden:
    priority: 1
    runs: true
  vscode:
    priority: 1
    runs: false
  watchtower:
    priority: 2
    runs: true
    depends-on: [ntfy]
