containers:
  homepage:
    priority: 1
    runs: true
  jellyfin:
    priority: 1
    runs: false
  navidrome:
    priority: 1
    runs: true
  nginx:
    priority: 0
    runs: true
  ntfy:
    priority: 2
    runs: true
  nextcloud:
    priority: 1
    runs: true
  pihole:
    priority: 1
    runs: true
  qbittorrent:
    priority: 1
    runs: false
  vaultwarden:
    priority: 1
    runs: true
  vscode:
    priority: 1
    runs: false
  watchtower:
    priority: 2
    runs: true
    depends-on: [ntfy]
